M48
; DRILL file KiCad 10.0.1 date 2026-05-15T14:17:38
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-15T14:17:38+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X58.5Y-94.5
X59.0Y-48.0
X162.5Y-71.0
T2
X60.5Y-40.5
X60.5Y-101.5
X133.5Y-40.5
X161.5Y-40.5
X161.5Y-101.5
M30
